AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
# AWS CloudFormation template formats
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-formats.html

# AWS CloudFormation Templates
# https://aws.amazon.com/cloudformation/resources/templates/

# https://github.com/aws-samples/s3-to-lambda-patterns/blob/master/translation/v2/template.yaml
# https://stackoverflow.com/questions/58167514/add-s3-trigger-on-a-lambda-function-with-cloudformation-yaml

Parameters:
  S3BucketName:
    Type: String
    Default: lambdax9

Resources:
  #** S3::Bucket **
  # Bucket 會自動 mb 或 rb
  # AWS::S3::Bucket
  MyBucketMonitor:
    Type: AWS::S3::Bucket
    DependsOn: MyInvokePermission
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html?icmpid=docs_cfn_console_designer
    Properties:
      BucketName: !Ref S3BucketName
      # AWS::S3::Bucket NotificationConfiguration
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-notificationconfig.html
      NotificationConfiguration:
        # AWS::S3::Bucket LambdaConfiguration
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-notificationconfig-lambdaconfig.html
        LambdaConfigurations:
          # Supported event destinations
        # https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-how-to-event-types-and-destinations.html#supported-notification-destinations
          - Event: s3:ObjectCreated:*
            Function: !GetAtt [ function, Arn]
          - Event: s3:ObjectRemoved:*
            Function: !GetAtt [ function, Arn]

  MyInvokePermission:
    Type: AWS::Lambda::Permission
    DependsOn: function
    Properties:
      FunctionName:
        Fn::GetAtt:
          - function
          - Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:s3:::${S3BucketName}

  MyBucketBackup:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lambdax9bak

  #** Serverless::Function **
  # 這段是表示將要上傳的 Lambda function, 此範例是用 python
  # AWS::Lambda::Function
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html?icmpid=docs_cfn_console_designer
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: function/.
      Description: Call the AWS Lambda API
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3FullAccess
      Tracing: Active
      Layers:
        - !Ref libs

  #** Lambda function libs **
  # Lambda function 需要使用的 libs, 於 create layer 時進行打包
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: HelloLambda-python-lib
      Description: Dependencies for the helloworld-python sample app.
      ContentUri: package/.
      CompatibleRuntimes:
        - python3.8

